mod capability;
mod loader;
mod module;
mod operation;
mod registry;
mod registry_service;
mod resource;
mod schema;
mod snapshot;
mod validation;

pub use capability::{CapabilityRequirementSet, CapabilitySet};
pub use loader::discover_modules;
pub use module::ModuleDescriptor;
pub use operation::{OperationBinding, OperationContract};
pub use registry::{InstanceRegistry, RegistryError};
pub use registry_service::RegistryService;
pub use resource::{ResourceDescriptor, ResourceValidationError, validate_resource};
pub use snapshot::RegistrySnapshot;
pub use validation::{ValidationError, validate_module};
